In [3]:
# Importing a library 
# Make it as if you want it again and again in many places
import math as m
m.sqrt(10)

3.1622776601683795

In [32]:
# Numpy arrays are much faster than simple python lists

# Importing numpy
import numpy as np
a=[1,2,3]
a1=np.array(a)
print(a1)

# Makes array with all  zeroes uptill len 10 of datatype float
a2=np.zeros(10)
print(a2)
print(a2.dtype)
print()

# Makes array with all  zeroes uptill len 10 of datatype int
# Can be declared type which we want the variable
a2=np.zeros(10,int)
print(a2)
print(a2.dtype)
print()


# Making two d Arrays
twoD=np.zeros((2,3))
print (twoD)
print(twoD.shape)
print()

arr=np.arange(10)
print(arr)

[1 2 3]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
float64

[0 0 0 0 0 0 0 0 0 0]
int64

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
(2, 3)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
# Numpy Operations

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=arr1+arr2
print(arr3)

print(arr1-arr2)
print(arr1*arr2)
print(arr1**2)

print(arr1.mean())




[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 4 9]
2.0


In [50]:
# Two D numpy arrays
m1=np.array([[1,2],[3,4]])
m2=np.array([[10,20],[30,40]])

print (m1.dot(m2))
print(np.sum([[0, 1], [0, 5]], axis=1))


[[ 70 100]
 [150 220]]
[1 5]
